version: '3'
services:
  db:
    image: postgres:14.5-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: ash
    volumes:
      - .:/app
      - bundle_install:/usr/local/bundle
    ports:
      - 3000:3000
      - 3036:3036
    depends_on:
      - db
    stdin_open: true
    tty: true
  redis:
    image: redis:6.2.7-alpine
    volumes:
      - redis_data:/data
    ports:
      - 8000:8000
  localstack:
    image: localstack/localstack:1.2.0
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=ap-northeast-1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./tmp/localstack:/tmp/localstack
    ports:
      - 4566:4566

volumes:
  redis_data:
  bundle_install: